Check for confliction option when encrypting

diff --git a/chest b/chest
--- a/chest
+++ b/chest
@@ -15,13 +15,13 @@ usage() {
   echo "  -r       Remove original data after sending to chest."
   echo "  -l       List items in chest."
   echo "  -k [key] Set custom key."
-  exit
 }
 
 # Display usage if no args set
 if [ -z "$1" ]
 then
   usage
+  exit 1
 fi
 
 # Set defaults
@@ -65,6 +65,14 @@ item=$1
 # Encrypt
 if [ $encrypt = true ]
 then
+
+  # Check conflicting options
+  if [ $decrypt = true ]
+  then
+    echo "Error cannot use option d and e together"
+    usage
+    exit 1
+  fi
 
   # Input file
   in_file=$item
